services:
  redis:
    image: redis:latest
    container_name: redis
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./data/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery
    volumes:
      - .:/app
      - ./logs:/app/logs
    depends_on:
      - redis
      - mariadb
    environment:
      DOCKER: TRUE
    links:
      - redis
      - mariadb
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: web
    environment:
      DOCKER: TRUE
    volumes:
      - .:/app
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mariadb
    links:
      - redis
      - mariadb